rails/api/config/routes.rb
Rails.application.routes.draw do
  resources :breweries do
    resources :beers do
      resources :ratings, except: [:new, :edit, :update, :destroy]
    end
  end

  root 'breweries#index'
end

rails/api/app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :brewery
  has_many :ratings, dependent: :destroy
end

rails/api/app/models/brewery.rb
class Brewery < ActiveRecord::Base
  has_many :beers, dependent: :destroy
end

rails/api/app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :beer
end

rails/api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token

  before_action :verify_user_id

  def verify_user_id
    if current_user_id.nil?
      respond_to do |format|
        format.json { render json: { status: :error, message: t(:unauthorized) }, status: 403 }
        format.html { redirect_to "/users/sign_in" }
      end

      return false
    end
  end

  def current_user_id
    request.headers['HTTP_X_BOWTIE_USER_ID']
  end

  def render_json_error(message=nil, data=nil)
    render json: { status: :error, data: data, message: message || t(:failure_undescribed) }
  end

  def render_json_success(data=nil)
    render json: { status: :success, data: data }
  end
end

rails/api/app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    @brewery = Brewery.find(params[:brewery_id])
    @beers   = @brewery.beers

    respond_to do |format|
      format.json { render_json_success @beers }
      format.html { }
    end
  end

  def show
    @brewery = Brewery.find(params[:brewery_id])
    @beer    = @brewery.beers.find(params[:id])

    respond_to do |format|
      format.json { render_json_success @beer }
      format.html {
        @ratings = @beer.ratings
        @rating  = @beer.ratings.new
      }
    end
  end

  def new
    @brewery = Brewery.find(params[:brewery_id])
    @beer    = @brewery.beers.new

    respond_to do |format|
      format.html { }
    end
  end

  def create
    @brewery      = Brewery.find(params[:brewery_id])
    @beer         = @brewery.beers.new(beer_params)
    @beer.user_id = current_user_id

    respond_to do |format|
      if @beer.save
        format.json { render_json_success @beer }
        format.html { redirect_to brewery_beer_path(@brewery, @beer) }
      else
        format.json { render_json_error t(:beer_save_failure), @beer.errors }
        format.html { }
      end
    end
  end

  def edit
    @brewery = Brewery.find(params[:brewery_id])
    @beer    = @brewery.beers.find(params[:id])

    respond_to do |format|
      format.html { }
    end
  end

  def update
    @brewery = Brewery.find(params[:brewery_id])
    @beer    = @brewery.beers.where(user_id: current_user_id).find(params[:id])

    respond_to do |format|
      if @beer.update_attributes(beer_params)
        format.json { render_json_success @beer }
        format.html { redirect_to brewery_beer_path(@brewery, @beer) }
      else
        format.json { render_json_error t(:beer_save_failure), @beer.errors }
        format.html { render 'edit' }
      end
    end
  end

  def destroy
    @brewery = Brewery.find(params[:brewery_id])
    @beer    = @brewery.beers.where(user_id: current_user_id).find(params[:id])

    respond_to do |format|
      if @beer.ratings.where('user_id != ?', current_user_id).count > 0
        format.json { render_json_error t(:beer_cannot_remove) }
        format.html { redirect_to brewery_beer_path(@brewery, @beer), alert: t(:beer_cannot_remove) }
      else
        @beer.destroy
        format.json { render_json_success }
        format.html { redirect_to brewery_beers_path(@brewery), notice: t(:beer_remove_success) }
      end
    end
  end

  private
  def beer_params
    params.require(:beer).permit(:name, :description)
  end
end

rails/api/app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  def index
    @breweries = Brewery.all

    respond_to do |format|
      format.json { render_json_success @breweries }
      format.html { }
    end
  end

  def show
    @brewery = Brewery.find params[:id]
    @beers = @brewery.beers

    respond_to do |format|
      format.json { render_json_success @brewery }
      format.html { }
    end
  end

  def new
    @brewery = Brewery.new
    @brewery.user_id = current_user_id

    respond_to do |format|
      format.json { head 422 }
      format.html { }
    end
  end

  def create
    @brewery = Brewery.new brewery_params
    @brewery.user_id = current_user_id

    respond_to do |format|
      if @brewery.save
        format.json { render_json_success @brewery }
        format.html { redirect_to brewery_path(@brewery), notice: t(:brewery_create_success) }
      else
        format.json { render_json_error t(:brewery_create_failure), @brewery.errors }
        format.html { }
      end
    end
  end

  def edit
    @brewery = Brewery.where(user_id: current_user_id).find(params[:id])

    respond_to do |format|
      format.json { head 422 }
      format.html { }
    end
  end

  def update
    @brewery = Brewery.where(user_id: current_user_id).find(params[:id])

    respond_to do |format|
      if @brewery.update_attributes(brewery_params)
        format.json { render_json_success @brewery }
        format.html { redirect_to brewery_path(@brewery), notice: t(:brewery_update_success) }
      else
        format.json { render_json_error t(:brewery_update_failure), @brewery.errors }
        format.html { }
      end
    end
  end

  def destroy
    @brewery = Brewery.where(user_id: current_user_id).find(params[:id])

    respond_to do |format|
      if @brewery.beers.where('user_id != ?', current_user_id).count > 0
        format.json { render_json_error t(:brewery_destroy_failure) }
        format.html { redirect_to '/users/sign_in', notice: t(:brewery_destroy_failure) }
      else
        @brewery.destroy
        format.json { render_json_success }
        format.html { redirect_to breweries_path, notice: t(:brewery_destroy_success) }
      end
    end
  end

  private
  def brewery_params
    params.require(:brewery).permit(:name,
                                    :description,
                                    :city,
                                    :state,
                                    :country)
  end
end

rails/api/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
    @ratings = beer.ratings.order('created_at desc')

    respond_to do |format|
      format.json { render_json_success @ratings }
    end
  end

  def create
    @beer    = beer
    @brewery = brewery
    @rating  = beer.ratings.new rating_params

    respond_to do |format|
      if @rating.save
        format.json { render_json_success @rating }
        format.html { redirect_to brewery_beer_path(@brewery, @beer), notice: t(:rating_create_success) }
      else
        format.json { render_json_error t(:rating_save_failure), @rating.errors }
        format.html { }
      end
    end
  end

  private
  def rating_params
    params.require(:rating).permit(:comment, :rating)
  end

  def brewery
    Brewery.find(params[:brewery_id])
  end

  def beer
    brewery.beers.find(params[:beer_id])
  end
end

rails/api/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/api/app/views/beers/edit.haml
= simple_form_for [@brewery, @beer] do |f|
  = f.input :name
  = f.input :description
  = f.button :submit

rails/api/app/views/beers/index.haml
- @beers.each do |beer|
  .beer
    %h3= beer.name
    %p= beer.description

rails/api/app/views/beers/new.haml
= simple_form_for [@brewery, @beer] do |f|
  = f.input :name
  = f.input :description
  = f.button :submit

rails/api/app/views/beers/show.haml
%h3= @beer.name
%p= @beer.description

.ratings
  .index
    - @ratings.each do |rating|
      %span.comment= rating.comment
      %span.created_at= rating.created_at

  .create
    = simple_form_for [@brewery, @beer, @rating] do |f|
      = f.input :comment
      = f.input :rating
      = f.button :submit

rails/api/app/views/breweries/edit.haml
= simple_form_for @brewery do |f|
  = f.input :name
  = f.input :description
  = f.input :city
  = f.input :state
  = f.input :country
  = f.button :submit

rails/api/app/views/breweries/index.haml
- @breweries.each do |brewery|
  .brewery
    %h3= link_to brewery.name, brewery_path(brewery)
    %p= brewery.description

rails/api/app/views/breweries/new.haml
= simple_form_for @brewery do |f|
  = f.input :name
  = f.input :description
  = f.input :city
  = f.input :state
  = f.input :country
  = f.button :submit

rails/api/app/views/breweries/show.haml
%h3= @brewery.name
%p= @brewery.description

.beers
  .index
    - @beers.each do |beer|
      = link_to beer.name, [@brewery, beer]

rails/api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BowtieBeer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul class="breadcrumbs">
  <li><%= link_to "Home", root_path %></li>

  <% if @brewery && !@brewery.new_record? %>
    <li><%= link_to @brewery.name, brewery_path(@brewery) %></li>
  <% end %>

  <% if @beer && !@beer.new_record? %>
    <li><%= link_to @beer.name, brewery_beer_path(@brewery, @beer) %></li>
  <% end %>
</ul>

<ul class="options">
  <li><%= link_to "New Brewery", new_brewery_path %></li>

  <% if @brewery && !@brewery.new_record? %>
    <li><%= link_to "New Beer", new_brewery_beer_path(@brewery) %></li>
  <% end %>
</ul>

<%= yield %>

</body>
</html>